### ISSUE TITLE
Support flutter_map version 5.0.0

### ISSUE THREAD

**Issue by agelospanagiotakis** [ankiimation/flutter_map_animated_marker#3]
Because flutter_map_animated_marker 1.0.1 depends on flutter_map ^3.0.0 and no versions of flutter_map_animated_marker match >1.0.1 <2.0.0, flutter_map_animated_marker ^1.0.1 requires flutter_map ^3.0.0.
So, because egsa_map depends on both flutter_map ^5.0.0 and flutter_map_animated_marker ^1.0.1, version solving failed.

**Comment by ankiimation** [comment]
published new version (2.0.0) that supports flutter_map 6.1.0
Thanks 🫡
